version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: apt update -qq && apt install wget software-properties-common -y -qq && add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run:
          name: Download source code of dependencies
          command: wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.6.1.tar.gz http://prdownloads.sourceforge.net/scons/scons-3.0.5.tar.gz https://github.com/hfp/libxsmm/archive/master.zip
      - run: apt update -qq && apt install -y -qq g++-5 gfortran openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-10 libhdf5-openmpi-dev python3 python3-pip libmetis-dev libparmetis-dev m4 unzip git python cmake
      - run:
          name: Update submodules
          command: git submodule update --init
      - run: python3 -m pip install --upgrade pip && python3 -m pip install 'numpy>=1.12.0' lxml
      - run:
          name: Install Scons
          command: tar -xaf scons-3.0.5.tar.gz && cd scons-3.0.5 && python3 setup.py install --prefix=/usr && cd ..
      - run:
          name: Compile NetCDF
          command: tar -xaf netcdf-4.6.1.tar.gz && cd netcdf-4.6.1 && CC=h5pcc ./configure --prefix=/usr --enable-shared=no --disable-dap && make && make install && cd .. 
      - run:
          name: Compile libxsmm
          command: unzip master.zip && cd libxsmm-master && make generator && cp bin/libxsmm_gemm_generator /usr/bin && cd ..
      - run: scons compileMode=release order=6 parallelization=hybrid arch=dsnb compiler=gcc unitTests=fast -j2
      - run: scons compileMode=release order=6 parallelization=hybrid arch=dsnb compiler=gcc unitTests=fast check
      - run: scons equations=viscoelastic2 numberOfMechanisms=3 compileMode=release order=6 parallelization=hybrid arch=dsnb compiler=gcc unitTests=fast -j2
      - run: scons equations=viscoelastic2 numberOfMechanisms=3 compileMode=release order=6 parallelization=hybrid arch=dsnb compiler=gcc unitTests=fast check
      - run: scons compileMode=release order=6 parallelization=hybrid commThread=yes arch=dsnb compiler=gcc unitTests=fast -j2
      - run: scons compileMode=release order=6 parallelization=hybrid commThread=yes arch=dsnb compiler=gcc unitTests=fast check
      - run: scons compileMode=release order=6 parallelization=hybrid hdf5=yes arch=dsnb compiler=gcc unitTests=fast -j2
      - run: scons compileMode=release order=6 parallelization=hybrid hdf5=yes arch=dsnb compiler=gcc unitTests=fast check
      - run: scons compileMode=release order=6 parallelization=hybrid netcdf=yes hdf5=yes metis=yes commThread=yes arch=dsnb compiler=gcc unitTests=fast -j2
      - run: scons compileMode=release order=6 parallelization=hybrid netcdf=yes hdf5=yes metis=yes commThread=yes arch=dsnb compiler=gcc unitTests=fast check
      - run: scons compileMode=release order=6 parallelization=none arch=dsnb compiler=gcc unitTests=fast -j2
      - run: scons compileMode=release order=6 parallelization=none arch=dsnb compiler=gcc unitTests=fast check
      - run: scons compileMode=debug order=6 parallelization=hybrid arch=dsnb compiler=gcc unitTests=fast -j2
      - run: scons compileMode=debug order=6 parallelization=hybrid arch=dsnb compiler=gcc unitTests=fast check
      - run: scons compileMode=release order=6 parallelization=hybrid arch=ssnb compiler=gcc unitTests=fast -j2
      - run: scons compileMode=release order=6 parallelization=hybrid arch=ssnb compiler=gcc unitTests=fast check
      - run: scons compileMode=release order=6 parallelization=hybrid netcdf=yes hdf5=yes commThread=yes arch=ssnb compiler=gcc unitTests=fast -j2
      - run: scons compileMode=release order=6 parallelization=hybrid netcdf=yes hdf5=yes commThread=yes arch=ssnb compiler=gcc unitTests=fast check
      - run: scons compileMode=debug order=6 parallelization=hybrid arch=ssnb compiler=gcc unitTests=fast -j2
      - run: scons compileMode=debug order=6 parallelization=hybrid arch=ssnb compiler=gcc unitTests=fast check
